README.md

The repository does not have a direct link to a documentation so I've added the default godoc badge one.

Add GoDoc badge to readme

---

cmd/kaf/kaf.go

Seems to have been the idea with the brokersFlag already but since the new SchemaRegistryURL was added it did not work as I had expected.

cmd/kaf: Changed logic so cmdline always wins

---

cmd/kaf/group.go

found flag is a remnant from the time when ls command used to take a group name as an argument. This was removed in commit 19b9a5a9af646173f78c5497c4090d48f1983868 .

Remove dead code

---

cmd/kaf/consume.go

Current implementation uses oldest as default but documents newest as being the default.
This removes the "Default" from the doc string as it is shown by default. I think this is better than changing the default and surprising people.
Current output:
```sh
--offset string   Offset to start consuming. Possible values: oldest, newest. Default: newest (default "oldest")
```
**IMPORTANT** this is a Github edit commit. I have ZERO go knowledge but I think your tool is very useful! If my changes break anything I will close this and open an issue instead.
Thanks for your work!

fix: default consume offset

---

cmd/kaf/kaf.go
examples/sasl_plaintext.yaml

fix connection when use SASL PLAINTEXT; The doc is here [authentication_sasl_plain Doc](https://docs.confluent.io/current/kafka/authentication_sasl/authentication_sasl_plain.html)

fix SASL authentication when SSL encryption is not enabled (PLAINTEXT)

---

cmd/kaf/kaf.go
config.go

This PR enables a user to establish a secure client connection to the Kafka cluster using a TLS certificate and private key.

add support for TLS client certificate

---

cmd/kaf/kaf.go
config.go

Small fix for reading config
before
```sh
$ mkdir ~/.kaf
$ echo 'invalid config' > ~/.kaf/config
$ kaf -b localhost:9092 topics
Config { []} does not exist $ # <-- no new line here
```
after
```sh
$ kaf -b localhost:9092 topics
Invalid config: yaml: unmarshal errors:
line 1: cannot unmarshal !!str `invalid...` into kaf.Config
```

Fix reading config error

---

cmd/kaf/kaf.go
config.go
go.mod
go.sum

When working with multiple clusters sometimes it's useful to be able to temporarily use a different cluster without overwriting the current default one with `kaf config use-cluster`.  This introduces the `-c` and `--cluster` flags which allow the user to specify which cluster to use on the command line.  This mimics the way `kubectl` deals with "context" and `gcloud` deals with "project".
It also updates the `github.com/jhump/protoreflect` dependency so that we can build under go v1.13.  Otherwise you get:
```
go: github.com/jhump/protoreflect@v1.4.4 requires
google.golang.org/genproto@v0.0.0-20170818100345-ee236bd376b0: invalid pseudo-version: does not match version-control timestamp (2017-08-18T01:03:45Z)
```

Allow Cluster Override on Command Line

---

cmd/kaf/topic.go

`kaf topic create test-topic` panics.
Create topic is currently **broken** because `-c` is already in use. Get error:
> panic: unable to redefine 'c' shorthand in "create" flagset: it's already used for "compact" flag
This will fix it to use `-C` as shorthand for `--compact` instead of `-c`.
`kaf topic create -C test-topic-compact`

Update topic.go so `topic create` works again.

---

cmd/kaf/kaf.go
config.go

This PR adds support for customizing the Kafka version passed to sarama on a per-cluster basis.
This PR also bumps the default version down to `0.10.0.0`, in an attempt to provide wider support by default. Is this a change you would like to make? Or would you perhaps rather keep the default version at `1.1.0.0` and print an error message describing how to change the configured version?
(I also see the `go.mod` and `go.sum` files changed. I'm not familiar enough with building for Go to understand whether those changes are semantically significant, or undesired.)

Allow per-cluster conf of Kafka version passed to sarama

---

cmd/kaf/kaf.go

Implementing a way to connect to a Kafka broker with TLS without using client authentication

Allow TLS connection without client authentication

---

cmd/kaf/topic.go

The provided example for set-config does not work as is. First parameter should be topic name and second a string of key=value separated by commas.

set-config command example updated

---

cmd/kaf/group.go

If a partition does not have a leader, kaf is failing at topic describe.
This should catch the similar situation in getHighmarks and at least propagate the error out.
Current output:
```
% kaf topic describe partitionless-topic-name
Name:        partitionless-topic-name
Internal:    false
Compacted:   false
Partitions:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x4397408]
goroutine 6 [running]:
github.com/birdayz/kaf/vendor/github.com/Shopify/sarama.(*Broker).send(0x0, 0x4a3a080, 0xc0002eca60, 0xc0001d0301, 0x0, 0x0, 0x0)
/Users/mkunc/go/src/github.com/birdayz/kaf/vendor/github.com/Shopify/sarama/broker.go:663 +0x68
github.com/birdayz/kaf/vendor/github.com/Shopify/sarama.(*Broker).sendAndReceive(0x0, …
```

Report error when partition has no leader

---

cmd/kaf/config.go

Using promptui's functionality to search in a select list, which is pretty nice when you have a lot of clusters configured.

Enable search in config select-cluster.

---

cmd/kaf/group.go
cmd/kaf/topic.go

This enhances `group describe` a line showing the summed offsets and lags for the group, and enhances `topic describe` with a line showing the summed high-watermark. This is useful when running kaf under `watch` or when you have a lot of partitions and slow producers/consumers and it's hard to tell if they're making progress.

Show sums for groups and topics

---

README.md

Hi, 
I suggest a small improvement in README.
Thanks.

typo in kafka topic describe example

---

README.md
cmd/kaf/group.go
cmd/kaf/main_test.go

Adds a simple check to the `kaf group commit` cmd that exits if the consumer group is active. In local testing it was possible for me to set the offset for an active consumer 😬 , thus the change.
Also added a small example in the readme so its more explicit
I've been having problems running the tests locally so no tests atm, if anyone has any advice, please share! 🙇 Would be happy to add some test coverage in a follow up MR

Only allow group commit on empty consumergroups

---

go.mod
go.sum

Hello,
Regarding [this MR](https://github.com/birdayz/kaf/pull/159), I still find the issue.
I'm bumping the dependency to the latest one.

bump github.com/golang/protobuf dependency v1.4.2 -> v1.5.2

---

README.md

Installing binaries with `go get` is deprecated. I updated the readme to use `go install`

README: Installing binaries with `go get` is deprecated

---

.github/workflows/go.yml
README.md
cmd/kaf/kaf.go

Hi @birdayz 
I finally decided to try a first contribution for this project that has been so useful in the last year of my work.
I'm no go expert but I hope this is a good contribution and a good start.
As requested in #158 this PR:
- sets the `version` on Cobra root command as [per documentation](https://github.com/spf13/cobra/blob/master/user_guide.md#version-flag)
- The version and commit values will be replaced automatically at build time by GitHub action and [goreleaser using `ldflags`](https://goreleaser.com/customization/build/)
Output:
```
$> go build -v -ldflags "-s -w -X main.version=v2.0 -X main.commit=abc" ./cmd/kaf/
$> ./kaf --version
kaf version v2.0 (abc)
```

Add version flag to show the current version of the tool

---

cmd/kaf/config.go

It was helpful to interact with Kafka using kaf recent days though, some inconveniences appered when deeply using. Supporting highlight current selection as with shortter command will be great benifit to our team,which was Inspired by [nrm ls command](https://github.com/Pana/nrm#example).
Hope to be adopted！

support selection for current cluster && ls alias

---

cmd/kaf/produce.go
pkg/avro/schema.go

As it turns out, most of the heavy lifting was already done by the schemaCache implementation. If you think this approach is fine I would like to add support for avro keys as well.
Fixes #181

Adding support to produce avro encoded messages

---

cmd/kaf/kaf.go

Allow using `SASL` mechanisms other than `PLAIN` with `SASL_PLAINTEXT` security protocol.
This fixes https://github.com/birdayz/kaf/issues/212

Support SASL mechanisms with SASL_PLAINTEXT

---

cmd/kaf/consume.go

I wanted this, so I wrote it.
- Deprecate `--raw` flag of `consume` subcommand.
- Add `--output` flag to `consume` subcommand with support for `default` (the current default `tabwriter` based output format), `raw` (the current `--raw` impl.) and a new `json` format.
- New `json` output format is meant to output all metadata + payload and key in a JSON payload for easier use with `jq`.
- Maintained automatic decoding and embedding of JSON format keys and payloads, similar to `tabwriter` output.

feat(consume): add output flag to consume for full json output

---

cmd/kaf/group.go

I wanted to use the tool to copy offsets from one consumer group to another. But doing it one by one appeared to be very slow. 
This PR adds one feature and fixes one problem.
Feature is the parameter *--offset-map* of *kaf group commit* that you can use to specify partitions to offset mapping that will be commited in just one run.
The fix is about closing the Consumer Group at the end of the operation. Without closing, we had to wait approximately 10 seconds in order Kafka to realize that the Consume Group is really dead (not correctly disconnected).

feat(group): offset-map param to set different offsets per partitions

---

cmd/kaf/consume.go
cmd/kaf/kaf.go
examples/schema_registry_basic_auth.yaml
pkg/avro/schema.go
pkg/config/config.go

Adds a new optional config section `schema-registry-credentials` (including example). When set, a HTTP basic authentication header will be injected in calls to the schema registry.
Also enables the schema registry support when using a consumer group.
I don't usually write Go, so apologies if I broke any conventions. Thanks for the excellent tool!

feat: Support HTTP basic authentication for schema registry connections

---

cmd/kaf/topic.go

`cleanup.policy` can be a comma-separated list https://kafka.apache.org/documentation/#topicconfigs_cleanup.policy

Handle multiple cleanup policies

---

cmd/kaf/kaf.go
examples/sasl_v1_handshake.yaml
pkg/config/config.go

why: current kaf uses the older SASL handshake v0, where the SASL payload is sent unframed down the wire.  v1 uses the dedicated SASL Kafka RPCs.  This feature allows the user to opt for the v1.  The default remains as v0.

feat: Allow SASL handshake version to be influenced from config

---

cmd/kaf/oauth.go
examples/sasl_ssl_oauth.yaml
pkg/config/config.go

Although `scopes` is optional, some OIDC providers refuse to authenticate if scopes are not configured properly.

Allow specifying scopes in oauth config

---

.github/workflows/go.yml
cmd/kaf/group.go
go.mod
go.sum

In our Kafka clusters we do not allow auto-creation of Consumer Groups, as we want that to be a manual step. Given that, Kaf refuses to create a brand new consumer group because the Kafka API reports it's status as `Dead` when it doesn't exist at all. This change teaches Kaf how to create consumer group offsets in this situation.
I also added the "earliest" verb to the offset options as an alias to "oldest"... that's the verbiage that the Kafka provided tooling uses, so it's what we are most used to as well. (A nice to have for us... but not strictly necessary for this PR if you'd prefer not to incorporate it.) 
(To keep the logic simple, I used `slices.Contains()`, but the Go version of 1.18 in `go.mod` doesn't have the stdlib version of `slices` yet... I'm quite happy to switch that and …

Support creating new consumer groups, and add "earliest" offset

---

cmd/kaf/topic.go

This PR enhances the `lagCmd` function to improve its reliability and error reporting. The main changes are:
1. Added a check to detect and report cases where the consumer offset is greater than the high watermark. This helps identify potential inconsistencies in the data.
2. Improved error messages for better clarity when troubleshooting issues.
3. Enhanced resource management by ensuring the admin client is properly closed using `defer`.
4. Only report lag values greater than zero, reducing noise in the output.
5. Minor code improvements for readability (e.g., renaming variables).
These changes should make the lag calculation more robust and informative, especially in edge cases or when dealing with topic compaction or message retention scenarios.
Testing:
- Tested with normal scenarios …

Improve lag calculation and error handling in lagCmd

---

Dockerfile

Related issue #289 and PR #297 for Dockerfile. Thanks @k-wall for the Dockerfile!
This PR changes to use ENTRYPOINT instead of CMD in Dockerfile so that we can run, for example,
> docker run --rm -it kaf nodes
instead of
> docker run --rm -it kaf kaf nodes
This makes run ad-hoc commands easier.
Besides, we build image from scratch, so we have no other commands to run from the image.

Use ENTRYPOINT instead of CMD in Dockerfile

---

cmd/kaf/produce.go

`scanner.Bytes()` returns internal buffer which is reused. That results in corrupted messages as message value (internal buffer) is modified by `scanner` while being sent to kafka.

fix: Corrupted lines in produce cmd with 'line' mode

---

cmd/kaf/consume.go

[cmd/kaf/consume.go](https://github.com/birdayz/kaf/blob/50d01e97d7156d08cf89c40cc357f03494bf66fd/cmd/kaf/consume.go#L354): remove unnecessay nil check.
```
var slice []byte
if slice != nil && len(slice) > 0 {}
// is the same as
if len(slice) > 0 {}
```
because `len(slice)` where slice == nil is always equal to 0,
`staticcheck` will highlight this optimization with the following message:
```
cmd/kaf/consume.go:354:6: should omit nil check; len() for []byte is defined as zero (S1009)
```
for reference: [staticcheck S1009](https://staticcheck.dev/docs/checks#S1009)

remove unnecessary nil check

---

.github/dependabot.yml
Dockerfile

The current go build image was EOF once go 1.24 was released.
Update dependabot so it can automatically help keep your go image up to date

Update go image, allow dependabot to update docker file

---

README.md
cmd/kaf/consume.go
cmd/kaf/consume_test.go
cmd/kaf/message.go
cmd/kaf/produce.go

**PR adds support for pipes.** 
Output of kaf consume can be used as input for kaf produce. 
This is possible by adding `json-each-row` input/output format.
```
echo {"data":1} | kaf produce mqtt.messages.incoming --key 1 --header h1:hv1
> Sent record to partition 0 at offset 0.
kaf consume mqtt.messages.incoming --output json-each-row
> {"topic":"mqtt.messages.incoming","partition":0,"offset":0,"timestamp":"2025-07-04T12:53:46.841+02:00","headers":[{"key":"h1","value":"hv1"}],"key":"1","payload":"{data:1}"}
echo '{"topic":"mqtt.messages.incoming","partition":0,"offset":0,"timestamp":"2025-07-04T12:53:46.841+02:00","headers":[{"key":"h1","value":"hv1"}],"key":"1","payload":"{data:1}"}' | kaf produce mqtt.messages.incoming --input json-each-row
kaf consume mqtt.messages.incoming --output …
```

Add support for pipes and consume --header flag to filter out messages by defined headers
