birdayz/kaf

- cmd/kaf/consume.go
Since kaf consume spawns a goroutine per partition, and writes to stderr or stdout in (potentially) three different places, there is a chance that the outputs from different messages become jumbled up.
This PR ensures that everything is written out in one unit.
> cmd/kaf: Synchronize stderr and stdout in consume

- README.md
- cmd/kaf/kaf.go
- config.go
- examples/README.md
- examples/basic.yaml
- examples/sasl_ssl.yaml
- examples/sasl_ssl_custom_ca.yaml
- examples/sasl_ssl_insecure.yaml
```
clusters:
- name: test
brokers:
- localhost:9092
SASL:
mechanism: PLAIN
username: admin
password: mypasswordisnotsosimple
TLS:
cafile: /path/ca.pem
verify: true
security-protocol: SASL_SSL
```
> add TLS config

- cmd/kaf/group.go
This PR addresses #7 and shows the number of messages the consumer is behind per partition.  It also fixes two minor issues `go vet` flagged in the same file.
> Additional Consumer Stat

- cmd/kaf/kaf.go
add command flag to turn on sarama logging for bug.
```shell
-v, --verbose                  Whether to turn on sarama logging
```
> add command flag to turn on sarama logging 

- cmd/kaf/config.go
- cmd/kaf/consume.go
- cmd/kaf/group.go
- cmd/kaf/kaf.go
- cmd/kaf/node.go
- cmd/kaf/produce.go
- cmd/kaf/topic.go
Replace the panics with printing the error to stderr and a non zero exit code.
Should fix #10 and #37
> always exit on error instead of panic

- cmd/kaf/consume.go
1. print Partition/Offset/Timestamp when message Key is nil; 
```sh
Partition:   0
Offset:      2
Timestamp:   2019-06-19 12:57:23.832 +0800 CST
hello
```
2. fix print headers panic when value is nil
```sh
Headers:
Key: Hello      Value: World
Key: OnlyKey       Value:
Partition:   0
Offset:      5
Timestamp:   2019-06-19 13:10:03.411 +0800 CST
hello
```
> print Partition/Offset/Timestamp when message Key is nil; fix print headers panic when value is nil

- cmd/kaf/consume.go
>  Consumer command panics sometimes with broker not connected

- cmd/kaf/topic.go
Result:
*topic create*
```
$ ./kaf topic create foo2
✅ Created topic!
Topic Name:            foo2
Partitions:            1
Replication Factor:    1
Cleanup Policy:        delete
```
*topic delete*
```
ᐅ ./kaf topic delete foo2
✅ Deleted topic foo2!
```
> prettier output for topic create, delete

- config.go
Issue: https://github.com/birdayz/kaf/issues/86
> Removed mutation of currentClusters.Brokers .

- README.md
- cmd/kaf/completion.go
- cmd/kaf/config.go
- cmd/kaf/consume.go
- cmd/kaf/group.go
- cmd/kaf/kaf.go
- cmd/kaf/node.go
- cmd/kaf/topic.go
Issue https://github.com/birdayz/kaf/issues/14
I've added bash autocompletion and fixed some minor issues.
> note that it can be slow to get the list of topics. maybe add caching?
Not sure if this is a good idea. How would you manage such cache? What user should do to update his list of topics?
> Add bash/zsh autocompletion

- cmd/kaf/config.go
Signed-off-by: shuangmin <konkacsm@gmail.com>
> [opt] add remove-cluster config cmd

- cmd/kaf/produce.go
Just quick few minutes hack to allow to set custom message headers. It has some limits: similar to key flag, string/value has to be string type and semicolon is used as separator thus cannot be used in key name. This can be improved later (and I hope I can find some time to do it), but it should be already useful even in such limited form.
> Add producer option to append custom headers

- examples/ssl_keys.yaml
An example like this was missing. (I looked at the code and this seems to work.)
> Add example of configuration with public/private key

- README.md
- cmd/kaf/completion.go
> powershell autocompletion

- README.md
- cmd/kaf/completion.go
- cmd/kaf/config.go
- cmd/kaf/consume.go
- cmd/kaf/group.go
- cmd/kaf/produce.go
- cmd/kaf/query.go
- cmd/kaf/topic.go
- cmd/kaf/valid.go
> some other completions

- cmd/kaf/group.go
> peek messages from consumer group offset

- cmd/kaf/produce.go
> produce byline

- README.md
- examples/README.md
- Copied out cheat-sheet commands from main README gif into examples/README.md
As [requested here](https://github.com/birdayz/kaf/issues/143)
This is my first open-source PR so apologies in advance for the inevitable rookie mistakes. Eager learn the community norms
> Documentation: cheat-sheet examples from Gif written out

- cmd/kaf/kaf.go
- cmd/kaf/oauth.go
- examples/sasl_ssl_oauth.yaml
- go.mod
- go.sum
- pkg/config/config.go
1. Changed config for oauth specific variables
2. Token is fetched using https://pkg.go.dev/golang.org/x/oauth2/clientcredentials
3. TokenCache is implemented
> Added OAUTH for kafka

- cmd/kaf/consume.go
- cmd/kaf/kaf.go
- go.mod
- go.sum
> feat: Add optional msgpack deserializer

- cmd/kaf/consume.go
- Added tail functionality. Allows reading the last n messages in a partition
- Adjusted follow functionality. Follow now conforms to the standard other programs
use. Without this flag, consume will stop at the high watermark of a partition.
With the flag, consume will wait for new messages after it reaches the high watermark
- Fixed limit-messages functionality. This parameter can now be used with the offset
parameter when set to newest or oldest
> Update additional consume functionality

- README.md
🤦‍♂️
Instead of `go install` I wrote `go get install` in my prev. commit.
Sorry about that
> fixing #164: wrong command

- cmd/kaf/produce.go
Adding support for avro encoded keys as well
> Adding avro key encoding

- cmd/kaf/topic.go
fixes https://github.com/birdayz/kaf/issues/208
> fix: Set exit flag when create/delete command fails

- README.md
Some people may find the usage of group offset reset confusing, so I have provided a complete usage example to clarify how it works.
https://github.com/birdayz/kaf/issues/263
> feature: add more usage example

- cmd/kaf/topic.go
Hi, It's been discussed at https://github.com/birdayz/kaf/issues/209 .
I've implemented a command that calculates the total lag for each consumer group, making it easier to inspect total lag by a topic dimension.
> feature: show total lags of each consumer

- cmd/kaf/topic.go
This commit introduces the `removeConfig` command, allowing users to remove specified attributes from a Kafka topic's configuration. The command takes the topic name and a comma-separated list of attributes to remove. It retrieves the current topic configuration, filters out the specified attributes, and updates the topic configuration accordingly.
> Add removeConfig command to manage topic attributes

- cmd/kaf/group.go
if client is able to ListConsumerGroups but  not authorized to DescribeConsumerGroups, then print the consumer group name only.
before this change, when execute the following command on Kafka server with the user that have access only on some group prefix. the command will exit without return any information
```
kaf group ls
Unable to describe consumer groups: kafka server: The client is not authorized to access this group
```
after apply the change, the group ls command will only show the list of consumer group
```
kaf group ls
NAME
test-group1
test-group2
test-group3
```
> group/ls: add fallback logic to show only group name
